# Generated by Django 6.0.6 on 2026-07-09 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена от')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена до')),
                ('min_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год от')),
                ('max_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год до')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('frequency', models.CharField(choices=[('instant', 'Мгновенно'), ('daily', 'Раз в день'), ('weekly', 'Раз в неделю')], default='instant', max_length=20, verbose_name='Частота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее уведомление')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.brand', verbose_name='Марка')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.model', verbose_name='Модель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created_at'],
            },
        ),
    ]
